### PR TITLE
Update the way we import the javascript file.

### PR DESCRIPTION
**Pull request by tfossoul**
Note that your module is not complete. If you click on "search more" button, you always have the "create" button on the top. Do you know how to remove it ?

### CODE REVIEW

**Comment by tfossoul** [comment]
I don't know if the file : view.xml is also on the pull request ?..

**Comment by vaab** [comment]
May I add that this new way of including javascript is not available until `saas-5` branch AFAIK.

**Comment by njeudy** [comment]
Hello, 

Why do you think I had to change the way including it .. with this new method, this module will not be ok for saas-3, saas-4 branch ..

I there a technical reason ?

thank for your comment.

**Comment by tfossoul** [comment]
Take the last odoo trunk version, install it, install your module, then try to modify a many2one field. Or check in your "chrome developper tools"(or firefox..) in "odoo debug mode", You'll see your javascript file is not included on the web page so nothing will work... 

They change the ways odoo import the css and javascript to improve the web's module... 
Check for instance the hr_timesheet_sheet : https://github.com/odoo/odoo/blob/master/addons/hr_timesheet_sheet/__openerp__.py
https://github.com/odoo/odoo/blob/master/addons/hr_timesheet_sheet/views/hr_timesheet_sheet.xml

:-)

**Comment by tfossoul** [comment]
I thinks this new ways of import come like one week before the "odoo days" ..

**Comment by njeudy** [comment]
Ok, so this old include way is removed from odoo ? it does'nt work anymore ?
I will try this .. thanks for the report

**Comment by tfossoul** [comment]
BTW : I don't know since it's like that but : there is natively these options : options="{'no_create': True}"
And like i ask it before : If you click on "search more" button, you always have the "create" button on the top. Do you know how to remove it ?

**Comment by njeudy** [comment]
I merge your proposal and open an new issue:

https://github.com/0k/web_m2x_options/issues/3

Nicolas JEUDY

Expert Technique et Fonctionnel Système d'Information
TUXSERVICES

22 rue du seminaire - 25170 Pelousey
e-mail : njeudy@tuxservices.com
mob. : +33 (0)6 28 95 36 64
http://www.tuxservices.com

2014-06-25 21:36 GMT+02:00 tfossoul notifications@github.com:

**Pull request merged**
